---
parameters:
- name: ASSISTED_SERVICE_IMAGE
  value: quay.io/app-sre/assisted-service
- name: IMAGE_TAG
  value: ''
  required: true
#- name: BASE_DNS_DOMAINS # example: name1:id1/provider1,name2:id2/provider2
#  value: ''
#  required: true
- name: OPENSHIFT_INSTALL_RELEASE_IMAGE
  value: "quay.io/openshift-release-dev/ocp-release@sha256:eab93b4591699a5a4ff50ad3517892653f04fb840127895bb3609b3cc68f98f3"
  required: true
- name: JWKS_URL # example https://example.com/.well-known/jwks.json
  value: "https://api.openshift.com/.well-known/jwks.json"
  required: true
- name: ALLOWED_DOMAINS
  value: 'https://qaprodauth.cloud.redhat.com/' #FIXME:yoni, change to empty string
  required: true
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-service
    namespace: assisted-installer
  spec:
    selector:
      matchLabels:
        app: assisted-service
    replicas: 1
    template:
      metadata:
        labels:
          app: assisted-service
      spec:
        serviceAccountName: assisted-service
        containers:
          - name: assisted-service
            image: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 200m
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 400Mi
            ports:
              - name: assisted-svc
                containerPort: 8090
            env:
              - name: ROUTE53_SECRET
                valueFrom:
                  secretKeyRef:
                    key: route53_secret
                    name: route53-creds
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: assisted-installer-s3
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: assisted-installer-s3
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: assisted-installer-s3
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: assisted-installer-s3
              - name: S3_ENDPOINT_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-s3
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    key: db.host
                    name: assisted-installer-rds
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: db.name
                    name: assisted-installer-rds
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    key: db.password
                    name: assisted-installer-rds
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    key: db.port
                    name: assisted-installer-rds
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    key: db.user
                    name: assisted-installer-rds
              - name: IMAGE_BUILDER_CMD
                value: ""
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: assisted-service
    name: assisted-service
    namespace: assisted-installer
  spec:
    ports:
      - name: assisted-svc
        port: 8090
        protocol: TCP
        targetPort: 8090
    selector:
      app: assisted-service
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: assisted-service-config
    namespace: assisted-installer
    labels:
      app: assisted-service
  data:
    SERVICE_BASE_URL: "http://assisted-service:8090"
    #BASE_DNS_DOMAINS: ${DOMAINS}
    OPENSHIFT_INSTALL_RELEASE_IMAGE: ${OPENSHIFT_INSTALL_RELEASE_IMAGE}
    ENABLE_AUTH: "true"
    JWKS_URL: ${JWKS_URL}
    ALLOWED_DOMAINS: ${ALLOWED_DOMAINS}
